#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SupermarketModelMySql;

namespace SupermarketModelMySql	
{
	[Table("measures")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class Measure
	{
		private int measureID;
		[Column("MeasureID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer")]
		[Storage("measureID")]
		public virtual int MeasureID
		{
			get
			{
				return this.measureID;
			}
			set
			{
				this.measureID = value;
			}
		}
		
		private string measureName;
		[Column("MeasureName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 45, Scale = 0, SqlType = "nvarchar")]
		[Storage("measureName")]
		public virtual string MeasureName
		{
			get
			{
				return this.measureName;
			}
			set
			{
				this.measureName = value;
			}
		}
		
		private IList<Product> products = new List<Product>();
		[Collection(InverseProperty = "Measure")]
		[Storage("products")]
		public virtual IList<Product> Products
		{
			get
			{
				return this.products;
			}
		}
		
	}
}
#pragma warning restore 1591
