#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SupermarketModelMySql;

namespace SupermarketModelMySql	
{
	[Table("vendors")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class Vendor
	{
		private int vendorID;
		[Column("VendorID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer")]
		[Storage("vendorID")]
		public virtual int VendorID
		{
			get
			{
				return this.vendorID;
			}
			set
			{
				this.vendorID = value;
			}
		}
		
		private string vendorName;
		[Column("VendorName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 100, Scale = 0, SqlType = "nvarchar")]
		[Storage("vendorName")]
		public virtual string VendorName
		{
			get
			{
				return this.vendorName;
			}
			set
			{
				this.vendorName = value;
			}
		}
		
		private IList<Product> products = new List<Product>();
		[Collection(InverseProperty = "Vendor")]
		[Storage("products")]
		public virtual IList<Product> Products
		{
			get
			{
				return this.products;
			}
		}
		
	}
}
#pragma warning restore 1591
